### PR TITLE
Add a precompile workload

### PR DESCRIPTION
**Pull request by jlapeyre**
On my laptop, the first execution time of the example in the README after this commit is 2.3s.

The first execution time before this commit is 10.0s.

### CODE REVIEW

**Review by kshyatt-aws — COMMENTED** [review]
Thanks for adding this! I actually have a much larger set of precompile statements I hope to add in the very near future so some of this may end up superseded, but no reason not to merge it now.

**Comment by kshyatt-aws** [comment]
FWIW on my M2 the README with no precompile statements runs in 4s, not 10s.

**Comment by jlapeyre** [comment]
I meant to put version info in the comment, but neglected to. The timing was under Julia 1.11.0
on a Ryzen 7 PRO 8840HS.

The ratio of 10s to 4s is surprising.

I guess that all the re-compilation that happens even with the precompilation is related the computation in `__init__`. I wouldn't be surprised if you have some tricks to get around it. Anyway, committing this now might make this more ergonomic for people trying it out.

**Comment by kshyatt-aws** [comment]
Yeah, agreed re: trying it out. I'll make a PR with more precompile workloads soon. Thanks for adding this!

**Pull request merged**
